### ISSUE TITLE
Problem about short hair

### ISSUE THREAD

**Issue by Zhzet9611** [GAP-LAB-CUHK-SZ/HairStep#10]
Great work! But when i test your net to generate some short hair just like follow one, i cant get a satisfactory results.
Maybe it caused by dataset which used for train or other factors ？
![3](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/35245026/8ceab58e-a7a2-4a7b-9449-053b7f58ee13)
![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/35245026/d177fc9f-411f-4f5a-adc1-6a433c0f44a7)

Also, Could you tell me how to get the colorful 3d strands in your paper through Blender?

**Comment by liuzgit** [comment]
I have the same problem, when I try to inference a picture of men with short hair, the result is also a long hair at the back of the head. I checked the data set and found that the proportion of long-haired women is much larger than that of short-haired men. Is it possible that this is the reason?

**Comment by PAULYZHENG** [comment]
Thanks for your interests! The issue of the reconstruction of short hair also bothers me.

I think @liuzgit is correct. The imbalance of the dataset is the main reason. However, so far, we do not have other data to use. An alternative solution is to add the mask of the back view as an extra channel fo the input. To achieve this, you may need to train a model to predicet the mask of the back. 

I have successfully trained a [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) network to remove the body and inpaint the occluded part. An testing example for short hair is shown as below. I think it will also work for only predicting the mask.
![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/28347316/97706e6c-2427-4a7f-a3e5-a01c7ac40d7d)

@Zhzet9611 As for the visulization of 3D strands, sorry I cannot release my rendering setting currently. You may try this excellent [renderer](https://github.com/Jhonve/HairStrandsRendering).

Hope this helps.

**Comment by Zvyozdo4ka** [comment]
> I think @liuzgit is correct. The imbalance of the dataset is the main reason. However, so far, we do not have other data to use. An alternative solution is to add the mask of the back view as an extra channel fo the input. To achieve this, you may need to train a model to predicet the mask of the back.
> 
> I have successfully trained a [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) network to remove the body and inpaint the occluded part. An testing example for short hair is shown as below. I think it will also work for only predicting the mask.


Could you share how did you achieve this?

 ![image](https://user-images.githubusercontent.com/28347316/265213249-97706e6c-2427-4a7f-a3e5-a01c7ac40d7d.png)
> 

is there any description of training process? 

![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/74532816/e4865a64-644d-45ca-a1ca-0ffae892d958)

I got these results on my samples, but the guy's hair from paper was reconstructed well. Also i checked landmarks, depth_map and segments. All worked fine except the image with glasses:

![professor_resized_512](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/74532816/4267a1e5-e3e7-4c52-a461-065272f13a54)

But depth map segmented correctly:
![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/74532816/4f390e13-439d-4d74-8b2e-5a37d527df26)

But 3D reconstruction of corresponding depth_map images above, looks like this:

![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/74532816/f2b5db95-815a-4191-bbd2-25137c1cfea7)

The original photos were these ones:
![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/74532816/3a152bbd-dae6-41a8-afaa-a3606bf43c92)

I would appreciate any ideas how to solve these problems
