### ISSUE TITLE
head model is present in hair3d ply file

### ISSUE THREAD

**Issue by op10ds** [GAP-LAB-CUHK-SZ/HairStep#15]
I noticed that, in the examples you provide, the male reconstructions in the hair3d folder have the shape of the head inside. 
![Immagine 2023-09-06 143728](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/143408589/2b306205-bfd0-415e-8da9-53672768c59b)
This does not appen for what concerns the female hair3d reconstructions.
![Immagine 2023-09-06 143827](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/143408589/d80e42ac-17ee-4454-afd8-68f8ce0e2121)

Is it possible to get the hair only obj in the male models as well?

**Comment by PAULYZHENG** [comment]
I do not know why this happened. It seems like that you used all vertices of the head model as hair roots in your upper example. Please check whether you pass correct args to this [function](https://github.com/GAP-LAB-CUHK-SZ/HairStep/blob/main/lib/hair_util.py#L108). It should be './data/roots10k.obj'.

**Comment by op10ds** [comment]
The code is as it should be, i did not modify anything. In fact,  I tried on the images you provide and this problem only rise when male subjects with short hair are elaborated. So this problem does not happen on your side?

**Comment by PAULYZHENG** [comment]
Your results seems sparse. Normaly the number of vertices of a generated 3D hair ranges from 300k to 1000k. 

I guess your first case is 86a0c5ecca8721acb831a702880c519e.png. Below is my result which looks much more dense and does not have the issue you mentioned.

![image](https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/28347316/238ff4ab-e11f-49e4-89b9-fba34542f6ed)

Hope it helps.

**Comment by op10ds** [comment]
Ok, I suspect the checkpoints were sort of corrupted,then. I resolved by re downloading and reinstalling everything.
Thanks for your support.
