### ISSUE TITLE
How to handle short hair?

### ISSUE THREAD

**Issue by Bai426** [GAP-LAB-CUHK-SZ/HairStep#16]
Hi, Dr. Zheng and your team. Thank you very much for releasing this amazing work to us. I tested on my end and with my own images, your pipeline works very well for those long hair and some medium hair, although as you said the SAM sometimes failed. But the short hair is easy to have the issue as discussed in #10. You mentioned that you trained pix2pix network to get the back hair mask, but I am wondering how you use the visible hair mask and the back hair mask together as the input to your current model for prediction? Also, the depth and strand maps are from the front view, so how you technically make the visible and invisible hair under this view? Then, how you merge or separately input them into the model for prediction? Thanks!

Best,
Mike

**Comment by PAULYZHENG** [comment]
Actually, you can directly use the back mask to cut the redundant back hair by projecting 3D hair strands to the image plane.
