### ISSUE TITLE
Multiple photos for a single haircut

### ISSUE THREAD

**Issue by nebis-software** [GAP-LAB-CUHK-SZ/HairStep#17]
Hi,
     I have starting testing this model and so far it provided very nice output, great work!
I was wondering if you are considering a possible extension where one can use multiple photos for a single haircut (like front, side, back): as far as I understand it, the model is currently forced to  "imagine" the hair that it doesn't see (like back hair), and such extension would help a lot.

Thanks!!

**Comment by PAULYZHENG** [comment]
Yes, it is totally doable. You may refer DeepMVSHair.
