### ISSUE TITLE
About Depth_syn 

### ISSUE THREAD

**Issue by CHANGXU12** [GAP-LAB-CUHK-SZ/HairStep#20]
Hello! Thank you so much for releasing this work! I have several questions and I would appreciate receiving responses.
1，Does Depth_syn network which uses StrandMap (GT) as input share the weight with RGB input?
2，Is "dense_depth_pred" in the dataset generated by the Depth_syn network using StrandMap (GT) or just the inference results?
Looking forward to the release of the training code.

**Comment by PAULYZHENG** [comment]
1. No, both of them are trained from scratch. The figure of pipeline si for better illustraction.
2. Just the inference results from real images with domain adaptation. 

Thanks for your interest.
