### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by ForrestPi** [GAP-LAB-CUHK-SZ/HairStep#25]
when running CUDA_VISIBLE_DEVICES=0 python -m scripts.recon3D 
error occurred

error cannot marching cubes
cannot unpack non-iterable int object

**Comment by ForrestPi** [comment]
@PAULYZHENG  Hi  could you provide some tips?

**Comment by kmlee307** [comment]
Hi, I got same error.  Did you fix it?

**Comment by xuetingl112358** [comment]
For people who had similar issue, follow [here](https://github.com/facebookresearch/pifuhd/issues/85#issuecomment-1336467047) and change [line 46 in sdf.py](https://github.com/GAP-LAB-CUHK-SZ/HairStep/blob/main/lib/mesh_util.py#L46) accordingly.
