### ISSUE TITLE
Meaning of the camera parameter

### ISSUE THREAD

**Issue by kmlee307** [GAP-LAB-CUHK-SZ/HairStep#4]
Hi.
First of all, thank you for the release of datasets.

I am curious about the meaning of the camera parameter, especially 'R' which is 3x3 matrix.
Could you notate the specific meaning of the each parameter of camera?

thx.

**Comment by PAULYZHENG** [comment]
This parameter is for projecting3D points to image plane to obtain the local image features. We use the same camera setting as PIFu (orthogonal). You can check PIFu's repo to figure out how to use it.
