### ISSUE TITLE
About visual result

### ISSUE THREAD

**Issue by liuzgit** [GAP-LAB-CUHK-SZ/HairStep#9]
Amazing work! However, when I imported the generated obj into the software, I could not get a good visual effect. Could you please tell me how to get the same visual result as the picture in your paper

**Comment by PAULYZHENG** [comment]
I use blender to render the 3D strands. You can also try this excellent [renderer](https://github.com/Jhonve/HairStrandsRendering) which supports binary hair file(.data) like the data in USC-HairSalon.

**Comment by Unturned3** [comment]
> I use blender to render the 3D strands. You can also try this excellent [renderer](https://github.com/Jhonve/HairStrandsRendering) which supports binary hair file(.data) like the data in USC-HairSalon.

May I ask how do you render the hairs using blender? I can import it into blender, but it shows up as a black blob.

**Comment by Akashpanchal95** [comment]
@Unturned3, Same I have used Blender to import the strand data and it shows a black blob.
Do you know how to generate the standmap and depthmap from USC-Hairsalon data?
